application: nerdpubtrivia
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- remote_api: on

libraries:
- name: django
  version: "1.2"

handlers:
- url: /
  static_files: index.html
  upload: index.html 

- url: /js
  static_dir: js

- url: /images
  static_dir: images
- url: /admin/.*
  script: SiteAdmin.app
