application: nerdpubtrivia
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on
- datastore_admin: on
- remote_api: on

handlers:
- url: /
  static_files: index.html
  upload: index.html 

- url: /images
  static_dir: images
