application: nerdpubtrivia
version: 1
runtime: python27
threadsafe: no
#runtime: python
api_version: 1

builtins:
- appstats: on
#- datastore_admin: on
- remote_api: on

libraries:
- name: django
  version: latest

handlers:
- url: /
  static_files: index.html
  upload: index.html 

- url: /images
  static_dir: images

- url: /admin/.*
  script: SiteAdmin.py
